### ISSUE TITLE
Renaming or disabling entities tables

### ISSUE THREAD

**Issue by StasGoshtein** [alexdebril/FeedIoBundle#19]
To keep on same naming conventions in the database, I'm trying to override entities tables names by extending your entity classes, but still my migration would create both your and my tables.

The quesrtion is: how to do it properly? Or how to disable entities creation in DB, since I use only read.

See example extending class:

`<?php

namespace DataBundle\Entity;

use Debril\FeedIoBundle\Entity\Feed as BaseFeed;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class RSSFeed
 * @package DataBundle\Entity
 * @ORM\Table(name="rss_feed")
 * @ORM\Entity()
 */
class RSSFeed extends BaseFeed
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
    }
}`

The resulting migration file then is:

`public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE element (id INT AUTO_INCREMENT NOT NULL, element_set_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, value VARCHAR(255) DEFAULT NULL, attributes LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', INDEX IDX_41405E3999EC048C (element_set_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE element_set (id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE feed (id INT AUTO_INCREMENT NOT NULL, element_set_id INT DEFAULT NULL, type SMALLINT DEFAULT 1 NOT NULL, comment LONGTEXT DEFAULT NULL, url LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, last_modified DATETIME NOT NULL, title VARCHAR(255) NOT NULL, link VARCHAR(255) DEFAULT NULL, public_id VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_234044AB99EC048C (element_set_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item (id INT AUTO_INCREMENT NOT NULL, feed_id INT DEFAULT NULL, element_set_id INT DEFAULT NULL, published_at DATETIME NOT NULL, created_at DATETIME NOT NULL, last_modified DATETIME NOT NULL, title VARCHAR(255) NOT NULL, link VARCHAR(255) DEFAULT NULL, public_id VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_1F1B251E51A5BC03 (feed_id), UNIQUE INDEX UNIQ_1F1B251E99EC048C (element_set_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media (id INT AUTO_INCREMENT NOT NULL, item_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, length VARCHAR(255) NOT NULL, INDEX IDX_6A2CA10C126F525E (item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rss_element (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, value VARCHAR(255) DEFAULT NULL, attributes LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rss_element_set (id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rss_feed (id INT AUTO_INCREMENT NOT NULL, type SMALLINT DEFAULT 1 NOT NULL, comment LONGTEXT DEFAULT NULL, url LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, last_modified DATETIME NOT NULL, title VARCHAR(255) NOT NULL, link VARCHAR(255) DEFAULT NULL, public_id VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rss_item (id INT AUTO_INCREMENT NOT NULL, published_at DATETIME NOT NULL, created_at DATETIME NOT NULL, last_modified DATETIME NOT NULL, title VARCHAR(255) NOT NULL, link VARCHAR(255) DEFAULT NULL, public_id VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rss_media (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, length VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE element ADD CONSTRAINT FK_41405E3999EC048C FOREIGN KEY (element_set_id) REFERENCES element_set (id)');
        $this->addSql('ALTER TABLE feed ADD CONSTRAINT FK_234044AB99EC048C FOREIGN KEY (element_set_id) REFERENCES element_set (id)');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E51A5BC03 FOREIGN KEY (feed_id) REFERENCES feed (id)');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E99EC048C FOREIGN KEY (element_set_id) REFERENCES element_set (id)');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C126F525E FOREIGN KEY (item_id) REFERENCES item (id)');
    }`

**Comment by alexdebril** [comment]
Hi, I think we'll need to dig Doctrine's documentation for that one. I'll let you know as soon as I find something about it.

**Comment by StasGoshtein** [comment]
@alexdebril , thanks a lot for that. Will appreciate your help. Let me know if you need more information.

**Comment by alexdebril** [comment]
It may be easier if you extends FeedIo\Feed directly. FeedIoBundle\Entity\Feed overrides it to support ORM functionalities, but if you have your own entity it's not mandatory to use FeedIoBundle's. 

The only loss is the type of the feed (external, public or private) and you'll have to set up the mapping yourself. 

Does it fit your needs?

**Comment by alexdebril** [comment]
ping @StasGoshtein  :-)

**Comment by alexdebril** [comment]
Hi,

I hope my answer helped you finding a solution. In the meantime I close this issue since it was answered a month ago, feel free to reopen it if needed.

Alex
